#ifndef BIGDATALAB1_HASHTABLE_H
#define BIGDATALAB1_HASHTABLE_H

#define HASHTABLE_SIZE 101

#define NLIST_NEXT  0
#define NLIST_NAME  8
#define NLIST_DEFN  16
#define NLIST_SIZE  24

#endif //BIGDATALAB1_HASHTABLE_H
